/**
 * Builds the immediate component requirements for one planned production order.
 * This helper deliberately performs no recursion or planning policy work.
 */

function createBomLineLookup(bom) {
  const lookup = new Map();
  const lines = bom && Array.isArray(bom.lines) ? bom.lines : [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line || typeof line.parentItemId !== "number") {
      continue;
    }

    if (!lookup.has(line.parentItemId)) {
      lookup.set(line.parentItemId, []);
    }
    lookup.get(line.parentItemId).push(line);
  }

  for (const childLines of lookup.values()) {
    childLines.sort((a, b) => {
      const lineA = Number(a.bomLineId);
      const lineB = Number(b.bomLineId);
      if (Number.isFinite(lineA) && Number.isFinite(lineB) && lineA !== lineB) {
        return lineA - lineB;
      }
      return String(a.bomLineId).localeCompare(String(b.bomLineId));
    });
  }

  return lookup;
}

/**
 * Converts a planned production recommendation into its direct material requirements.
 * Child demand is needed when the parent order is released, not when the sales order is due.
 *
 * @param {Object} plannedOrder Production recommendation generated by the existing policies
 * @param {Map<number, Object[]>} bomLineLookup Direct BOM lines grouped by parent item
 * @returns {Object[]} Immediate child requirements
 */
function buildChildRequirements(plannedOrder, bomLineLookup) {
  const childLines = bomLineLookup && bomLineLookup.get(plannedOrder.itemId);
  if (!childLines || childLines.length === 0) {
    return [];
  }

  const parentPath = Array.isArray(plannedOrder.path) ? plannedOrder.path : [plannedOrder.itemId];
  const requiredDate = plannedOrder.plannedReleaseDate instanceof Date
    ? new Date(plannedOrder.plannedReleaseDate.getTime())
    : new Date(plannedOrder.plannedReleaseDate);

  return childLines.map((line) => ({
    demandSourceType: plannedOrder.demandSourceType || "SALES_ORDER",
    salesOrderId: plannedOrder.salesOrderId,
    salesOrderLineId: plannedOrder.salesOrderLineId,
    itemId: line.childItemId,
    requiredQuantity: plannedOrder.quantity * line.qtyPerParent,
    requiredDate: new Date(requiredDate.getTime()),
    bomLevel: (typeof plannedOrder.bomLevel === "number" ? plannedOrder.bomLevel : 0) + 1,
    path: [...parentPath, line.childItemId],
  }));
}

module.exports = {
  createBomLineLookup,
  buildChildRequirements,
};
